# Generated by Django 5.2.7 on 2025-10-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тура')),
                ('video', models.FileField(upload_to='virtual_tours/', verbose_name='Видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
        ),
    ]
