# Generated by Django 5.2.7 on 2025-10-24 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Картинка')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
